import avatar from './assets/avatar.png';

export default {
  skinId: 'neighborhood',
  skin: {
    pegmanHeight: 52,
    pegmanWidth: 49,
    pegmanYOffset: -8,
    avatar
  },
  level: {
    startDirection: 0,
    serializedMaze: [
      [
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
      ],
      [
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
      ],
      [
        { tileType: 0 },
        { tileType: 2, value: '#ace' },
        { tileType: 0, value: '#ace'},
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0 },
        { tileType: 0 },
      ],
      [
        { tileType: 0 },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#f88'},
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#f88' },
        { tileType: 0, value: '#ace' },
        { tileType: 0 },
        { tileType: 0 },
      ],
      [
        { tileType: 0 },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0 },
        { tileType: 0 },
      ],
      [
        { tileType: 0 },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#f88' },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#f88' },
        { tileType: 0, value: '#ace' },
        { tileType: 0 },
        { tileType: 0 },
      ],
      [
        { tileType: 0 },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0, value: '#ace' },
        { tileType: 0 },
        { tileType: 0 },
      ],
      [
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
        { tileType: 0 },
      ],
    ],
  }
}
